/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary": "#135bec",
        "primary-hover": "#1d4ed8",
        "background-light": "#f8f9fc",
        "background-dark": "#101622",
        "card-light": "#ffffff",
        "card-dark": "#1a2230",
        "text-main-light": "#0d121b",
        "text-main-dark": "#f8f9fc",
        "text-secondary-light": "#4c669a",
        "text-secondary-dark": "#9ca3af",
        "border-light": "#e7ebf3",
        "border-dark": "#2d3748",
        // Existing colors for backward compatibility
        "on-primary-fixed-variant": "#003daa",
        "on-tertiary-fixed-variant": "#812800",
        "secondary-fixed": "#dbe1ff",
        "inverse-on-surface": "#f0f0fc",
        "tertiary-fixed-dim": "#ffb59b",
        "tertiary": "#902e00",
        "inverse-surface": "#101622",
        "background": "#f6f6f8",
        "inverse-primary": "#b4c5ff",
        "surface-container-highest": "#cfd7e7",
        "tertiary-fixed": "#ffdbcf",
        "on-surface": "#0d121b",
        "on-secondary-fixed-variant": "#2f4380",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#380d00",
        "surface-container-high": "#e7ebf3",
        "on-secondary-container": "#334885",
        "error-container": "#ffdad6",
        "on-background": "#0d121b",
        "on-secondary-fixed": "#00174c",
        "on-surface-variant": "#4c669a",
        "on-secondary": "#ffffff",
        "outline": "#cfd7e7",
        "error": "#ba1a1a",
        "surface": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#e2e6ff",
        "surface-container": "#ededf9",
        "surface-bright": "#ffffff",
        "on-primary-fixed": "#00174c",
        "surface-dim": "#d9d9e5",
        "outline-variant": "#e7ebf3",
        "surface-container-low": "#f6f6f8",
        "on-error-container": "#93000a",
        "surface-variant": "#e7ebf3",
        "secondary": "#485c9a",
        "primary-container": "#135bec",
        "tertiary-container": "#b93d00",
        "surface-tint": "#135bec",
        "on-tertiary-container": "#ffe1d7",
        "on-primary": "#ffffff",
        "secondary-container": "#a5b9fe",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "display": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
